---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resource-finalizer.argocd.argoproj.io
spec:
# Projects provide a logical grouping of applications which is useful when Argo CD is used by multiple teams
  project: default
  source: 
    repoURL: git@github.com/gauravgirase/privateAPP.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfheal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=forground
      - PruneLast=true